services:

# Blockscout database
  db:
    image: postgres:14
    restart: always
    container_name: 'postgres'
    healthcheck:
      test: [ "CMD", "pg_isready"]
      timeout: 45s
      interval: 10s
      retries: 10
    environment:
        POSTGRES_PASSWORD: ''
        POSTGRES_USER: 'postgres'
        POSTGRES_HOST_AUTH_METHOD: 'trust'
    # volumes:
    #   - postgres-data:/var/lib/postgresql/data
    ports:
      - 7432:5432

# # Redis db
  redis_db:
    image: 'redis:alpine'
    ports:
      - 6379:6379
    command: redis-server
    volumes:
      - redis-data:/data

# # Blockscout blockscanner
  blockscout:
    image: tmjeff/moscout
    restart: always
    depends_on:
      db:
        condition: service_healthy  
    container_name: 'blockscout'
    links:
      - db:database
    command: bash -c "bin/blockscout eval \"Elixir.Explorer.ReleaseTasks.create_and_migrate()\" && bin/blockscout start"
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    # env_file:
    #   -  ./envs/common-blockscout.env
    environment:
        ETHEREUM_JSONRPC_VARIANT: 'besu'
        ETHEREUM_JSONRPC_HTTP_URL: http://mineonlium:8545
        BLOCKSCOUT_HOST: 0.0.0.0
        PORT: 4000
        # ETHEREUM_JSONRPC_WS_URL: ws://34.87.231.138:8546/
        INDEXER_DISABLE_PENDING_TRANSACTIONS_FETCHER: 'true'
        FETCH_REWARDS_WAY: trace_block
        DATABASE_URL: postgresql://postgres:@db:5432/blockscout?ssl=false
        ECTO_USE_SSL: 'false'
        ETHEREUM_JSONRPC_TRACE_URL: http://mineonlium:8545/
        INDEXER_CATCHUP_BLOCKS_BATCH_SIZE: 250
        # SECRET_KEY_BASE: '56NtB48ear7+wMSf0IQuWDAAazhpb31qyc7GiyspBP2vh7t5zlCsF5QDv76chXeN'
        CHAIN_ID: '54321'
    ports:
      - 40001:4000

#NOT WORKING!! i think im just missing the compilers 
# # Smart Contract Verification
  smart-contract-verifier:
    image: ghcr.io/blockscout/smart-contract-verifier:${SMART_CONTRACT_VERIFIER_DOCKER_TAG:-latest}
    restart: always
    env_file:
      -  ./envs/common-smart-contract-verifier.env
    ports:
      - 8043:8043

volumes:
   redis-data:
  #  postgres-data: